packages:
  - 'apps/*'
  - 'packages/*'
  - 'extensions/*'
allowBuilds:
  '@serialport/bindings-cpp': true
  electron: true
  electron-winstaller: true
  esbuild: true
overrides:
  '@noble/hashes': '1.8.0'


